### ISSUE TITLE
VoIP i ministerstwa

### ISSUE THREAD

**Issue by Qrzysio** [skotniczny/phonePL#3]
Świetny regex, czy wciąż utrzymywany?

Jest kilka potrzebnych zmian:

- [x] Dla numerów stacjonarnych brakuje strefy numeracyjnej **47**.
> Oprócz wskaźników stref numeracyjnych (WSN) przydzielony został niegeograficzny wyróżnik sieci (WST) „39” dla usług wykorzystujących technologię IP (VoIP) oraz wyróżniki na potrzeby sieci telekomunikacyjnych Ministerstwa Spraw Wewnętrznych i Administracji („47”; największe zastosowanie ma w policji od stycznia 2020 r.[2]) i Ministerstwa Obrony Narodowej („26”). 

Za: https://pl.wikipedia.org/wiki/Numery_telefoniczne_w_Polsce

**Comment by skotniczny** [comment]
Zaktualizowane 09f9ead, dzięki!
